name: My First Callme Work flow.
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: false
      env_name:
        type: string
        required: false
env:
  IMAGE_NAME: ${{inputs.image_name}}
jobs:
  callme_job1:
    name: ${{inputs.env_name}}
    runs-on: ubuntu-latest
    steps:
      - run: |
         env
         echo "${{ secrets.SECRET_NAME }} "
