name: My First Callme Work flow.
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: false
      env_name:
        type: string
        required: false
    secrets:
      secret_name:
        required: false
env:
  IMAGE_NAME:  ${{inputs.image_name}}
  API_KEY:  ${{ secrets[format('{0}_API_KEY', secrets.secret_name)] }}
jobs:
  deploy:
    name: ${{inputs.env_name}}
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "yyyyyyyy   - ${{ secrets.STAGE_API_KEY }} "
         echo "eeeee - ${{ vars.YOURNAME }}"
          echo "FFFF  ----  ${{secrets.secret_name}}"
          echo "${{inputs.image_name}}"
         env
