name: My First Callme Work flow.
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: false
env:
  IMAGE_NAME: ${{input.image_name}}
jobs:
  callme_job1:
    name: callme_job1
    runs-on: ubuntu-latest
    steps:
      - run: env
