run-name: "First CICD  by @${{ github.actor }}"
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build_job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Building Nodejs
        uses: actions/setup-node@v3

      - name: Build
        run: |
          npm install
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "I am deploy"
      - name: Branch Name
        run: "echo running on BRANCH_NAME: ${{ github.base_ref || github.ref_name }}"