run-name: "First CICD  by @${{ github.actor }}"
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build_job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : GITHUB_REF_NAME
        run: "echo GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
      - name: GITHUB_REF_TYPE
        run: "echo GITHUB_REF_TYPE :  ${GITHUB_REF_TYPE}"
      - name: GITHUB_REF
        run: "echo GITHUB_REF :  ${GITHUB_REF}"
      - name: GITHUB_BASE_REF
        run: "echo GITHUB_BASE_REF :  ${GITHUB_BASE_REF}"

      - name: Building Nodejs
        uses: actions/setup-node@v3

      - name: Build

        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref_name }}
          npm install
  deploy:
    name: "deploy to develop"
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' &&  github.ref_name == 'develop'
    steps:
      - run: echo "I am deploy"
      - name: Branch Name
        run: "echo running on BRANCH_NAME: ${{ github.base_ref || github.ref_name }}"
