on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - stage
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'stage'
        type: choice
        options:
          - main
          - stage
          - prod

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
#        - uses: actions/checkout@master
#          with:
#            name: chinmaysahoo19/TesProject.git     <-- clone https://github.com/org1/repo1
        - run: |
            cd node-hello
            yarn install
            ls  -ltr
            git branch -a
            
