on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - stage
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'stage'
        type: choice
        options:
          - main
          - stage
          - prod

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: |
          echo  The tags are ${{ inputs.tags }}
          ls -altr
          ./.github/workflows/setupenv.sh
