on:
  workflow_dispatch:
env:
  INCREMENT_TYPE: patch
  #GITHUB_TOKEN: ${{ secrets.MYPAT }}
  GIT_SSH_PK: ${{ secrets.GIT_SSH_PK }}
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Env"
        run: |
          mkdir -p ~/.ssh
          echo "$GIT_SSH_PK" | base64 -d >~/id_rsa &&
          ssh-keyscan github.com > ~/.ssh/known_hosts
          cp ~/id_rsa  ~/.ssh/ && chmod -R 700 ~/.ssh && chmod -R 400 ~/.ssh/*
          #git clone git clone -c "core.sshCommand=ssh -i 360.key -o StrictHostKeyChecking=no "  git@github.com:chinmaysahoo19/CSCICD.git
          git clone   git@github.com:chinmaysahoo19/CSCICD.git
          pwd
          ls  -ltr

##      - uses: actions/checkout@v3
##        with:
##          fetch-depth: 0
##          ref: ${{ github.ref }}
##          token: ${{ secrets.MYPAT }}
##          ssh
##      - run: |
##          cd app
##          #yarn install
##          git tag
#          ../.github/workflows/git-utils.sh version-push
