on:
  workflow_dispatch:
env:
  INCREMENT_TYPE: patch
  GITHUB_TOKEN: ${{ secrets.MYPAT }}
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MYPAT }}
      - run: |
          cd app
          #yarn install
          git tag
          ../.github/workflows/git-utils.sh version-push
