on:
  workflow_dispatch:
env:
  INCREMENT_TYPE: patch
  #GITHUB_TOKEN: ${{ secrets.MYPAT }}
  GIT_SSH_PK: ${{ secrets.GIT_SSH_PK }}
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          #token: ${{ env.GITHUB_TOKEN }}
          ssh-key: ${{ secrets.GIT_SSH_PK }}
      - run: |
          cd app
          #yarn install
          git tag
          ../.github/workflows/git-utils.sh version-push
