on:
  workflow_dispatch:
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
#        - uses: actions/checkout@master
#          with:
#            name: chinmaysahoo19/TesProject.git     <-- clone https://github.com/org1/repo1
        - run: |
            cd node-hello
            yarn install
            ls  -ltr
            git branch -a
            
