on:
  workflow_dispatch:
env:
  INCREMENT_TYPE: patch
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd app
          #yarn install
          git tag
          ../.github/workflows/git-utils.sh version-push
